### ISSUE TITLE
editorOptions属性与默认值merge方法不当（数组合并时）

### ISSUE THREAD

**Issue by rexerwang** [FEMessage/v-editor#103]
## Describe the bug
`editorOptions`属性与默认值merge方法不当：数组合并时，应该覆盖之(overwrite)，而非合并。
场景：自定义toolbar栏，则会错乱。

https://github.com/FEMessage/v-editor/blob/4a5bbf3a6ad47f60896089a0ab20b995ca918266/src/v-editor.vue#L91

**Comment by levy9527** [comment]
收到，可能要下周才发版本了。
