### ISSUE TITLE
粘贴外链图片显示了两张同样的图片

### ISSUE THREAD

**Issue by JE-lee** [FEMessage/v-editor#41]
## Describe the bug
在编辑器中粘贴 从网站中复制的图片，显示了两张
其中一张为外链图片，另一张为上传了OSS的图片。

## To Reproduce
1. 复制网页图片
![image](https://user-images.githubusercontent.com/19794813/64507997-c0d99a80-d30e-11e9-907a-8b91b2a16cd8.png)

2. 在编辑器中粘贴

3. 出现了两张一样的
![image](https://user-images.githubusercontent.com/19794813/64508600-6a6d5b80-d310-11e9-9ae9-bd844903d04c.png)

## Expected behavior
两张图片分别为外链图片和上传了OSS的图片。
期望： 如果粘贴的是外链图片就不需要触发OSS上传了。

## suggestion
判断是单纯的截图还是从网页复制的图片
```javascript
paste(e) {
      if (
        !e.clipboardData.files.length ||
       // 当上述情况出现的时候，剪贴板里面有两种数据
      // 一组是图片的url:string, 一组是图片的元数据file
        (e.clipboardData.items.length > 1 && e.clipboardData.files.length)
      ) return
      this.$refs.uploadToAli.paste(e)
    }
```

## environment information
 - Version [e.g. 22] latest
 - OS: [e.g. iOS] win10
 - Browser [e.g. chrome, safari] chrome

**Comment by lianghx-319** [comment]
- 可以设置 `editorOptions = {pasteIgnoreImg: true}` 阻止编辑器默认粘贴图片，此时会默认将图片上传 oss，图片存放在自己的图床应该更佳。
- 如下图 editor 监听粘贴事件的时候会判断图片是否也需要粘贴
![image](https://user-images.githubusercontent.com/27187946/64800585-6a43b900-d5b9-11e9-905f-2f84621c24b6.png)
