### ISSUE TITLE
剪贴板粘贴图片进去后，在图片前回车，图片消失

### ISSUE THREAD

**Issue by DeepenLau** [FEMessage/v-editor#44]
## Describe the bug
剪贴板粘贴图片进去后，在图片前回车，图片消失

## Screenshots
![v-editor](https://user-images.githubusercontent.com/14030995/64939332-3f948180-d893-11e9-8fff-cc563f7f0a2e.gif)

## To Reproduce
1. 打开编辑器
2. 粘贴图片
3. 移动鼠标到图片前，按下回车

## Expected behavior
图片不消失

## environment information
 - Version 1.2.5
 - OS: MacOs
 - Browser chrome 76.0.3809.132

## Other
在 src/v-editor.vue:152，去除 editorValue 方法调用可以解决，但尚未知是否有其他副作用

**Comment by levy9527** [comment]
debug中...
