### ISSUE TITLE
在网页中直接复制图片然后粘贴到 v-editor 上传成功后会添加2次加入内容区域。

### ISSUE THREAD

**Issue by GranzonLin** [FEMessage/v-editor#50]
## Describe the bug
在网页中直接复制图片然后粘贴到 v-editor 上传成功后会添加2次加入内容区域。

## Screenshots
![guancongcaonima](https://user-images.githubusercontent.com/31909786/67470570-8b9bc880-f680-11e9-807a-3e2bf1cad622.gif)

## To Reproduce
1. 在网页中寻找一张图片进行右键
2. 复制图片，记住，是复制图片，不是复制图片地址哟！
3. 最后到达 v-editor ctrl + v 粘贴一下即可重现 ***bug***

## Expected behavior
粘贴图片只出现一次就好

## environment information
 - Version  77.0.3865.90（正式版本） （64 位）
 - OS: window10
 - Browser chrome

**Comment by levy9527** [comment]
请问，组件版本是多少。如果不是最新版本，试试升级至最新？

**Comment by GranzonLin** [comment]
> 请问，组件版本是多少。如果不是最新版本，试试升级至最新？

果然是版本问题，老的脚手架，不好意思，马上更新
