### ISSUE TITLE
bug: the content don't v-model

### ISSUE THREAD

**Issue by cjfff** [FEMessage/v-editor#55]
## Describe the bug
使用搜狗输入法输入内容，然后使用键盘数字键选择后，组件内部并没有同步数据

## Screenshots
![222](https://user-images.githubusercontent.com/20502762/70598504-f64f9600-1c25-11ea-8846-faba5579711d.gif)

## To Reproduce
1. 输入内容
2. 通过英文键盘上方数字选择内容
3. 点击其他空白位置

oh~ 恭喜你，会发现数据没同步 

## Expected behavior
希望数据能及时同步

## environment information
 - Version 1.2.9
 - OS: windows
 - Browser chrome

**Comment by levy9527** [comment]
这。。。请求换个输入法，2333😂
