### ISSUE TITLE
希望图片点击可以放大

### ISSUE THREAD

**Issue by wuyanping** [FEMessage/v-editor#8]
点击富文本框里面的图片，可以放大

**Comment by donaldshen** [comment]
1. 右键图片选择“在新标签页中打开”，你就可以随意缩放了，是否能满足你的需求？
2. 如果在当前页放大，那放大的效果是怎样？短边占满（cover）还是长边占满（contain）？要留边距加阴影吗？

**Comment by wuyanping** [comment]
1.右键图片选择“在新标签页中打开”，就可以随意缩放了，能满足需求
