### ISSUE TITLE
如果单单放截图，获取的数据是没有，一定要加点文字才能获取到数据

### ISSUE THREAD

**Issue by wuyanping** [FEMessage/v-editor#9]

**Comment by quixote1304629** [comment]
我也遇到了，这种问题
![image](https://user-images.githubusercontent.com/32378929/56630307-820ab700-6683-11e9-9e7d-e0eae4ce5a6b.png)
![image](https://user-images.githubusercontent.com/32378929/56630338-a4043980-6683-11e9-93b8-153dbdb87feb.png)
